version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: niftyzone_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
    # command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"

volumes:
  redis_data:
